

services:
  text2sql:
    build: .
    container_name: text2sql
    ports:
      - "8501:8501"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env  # This loads the environment variables from the .env file
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}  # Refers to MYSQL_PASSWORD from .env
      MYSQL_DATABASE: ${MYSQL_DATABASE}      # Refers to MYSQL_DATABASE from .env
  
    ports:
      - "3307:3306"                         # Exposes MySQL's default port to the host
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql           # Persist MySQL data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data: