

services:
  text2sql:
    build: .
    container_name: text2sql
    ports:
      - "8501:8501"
    depends_on:
      - mysql
    env_file:
      - .env  # This loads the environment variables from the .env file
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mShristy11"  # Refers to MYSQL_PASSWORD from .env
      MYSQL_DATABASE: ${MYSQL_DATABASE}      # Refers to MYSQL_DATABASE from .env
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
  
    ports:
      - "3307:3306"                         # Exposes MySQL's default port to the host
    networks:
      - mynetwork
    volumes:
      - mysql-db-data:/var/lib/mysql           # Persist MySQL data


networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-db-data: